apiVersion: kuscia.secretflow/v1alpha1
kind: DomainDataGrant
metadata:
  labels:
    kuscia.secretflow/domaindataid: demo-table
  name: demo-table
  namespace: kuscia-domain-alice
spec:
  author: kuscia-domain-alice
  domainDataID: demo-table
  grantDomain: kuscia-domain-bob
