---
apiVersion: v1
kind: Namespace
metadata:
  name: kuscia-domain-bob

---
apiVersion: v1
kind: Namespace
metadata:
  name: kuscia-domain-bob

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuscia-bob
  namespace: kuscia-domain-bob
  labels:
    app: kuscia-bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuscia-bob
  template:
    metadata:
      labels:
        app: kuscia-bob
    spec:
      containers:
        - command:
            - tini
            - --
            - kuscia
            - start
            - -c
            - etc/conf/kuscia.yaml
          env:
            - name: REGISTRY_ENDPOINT
              value: docker.io
            - name: NAMESPACE
              value: kuscia-bob
            - name: TZ
              value: Asia/Shanghai
          image: tonywu6/kuscia:linux-arm64
          imagePullPolicy: Never
          name: bob
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/kuscia/var/tmp
              name: kuscia-var-tmp
            - mountPath: /home/kuscia/etc/conf/kuscia.yaml
              name: kuscia-config
              subPath: kuscia.yaml
          workingDir: /home/kuscia
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
      automountServiceAccountToken: true
      volumes:
        - emptyDir: {}
          name: kuscia-var-tmp
        - configMap:
            defaultMode: 420
            name: kuscia-bob
          name: kuscia-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuscia-bob
  namespace: kuscia-domain-bob
  labels:
    app: kuscia-bob
data:
  kuscia.yaml: |-
    mode: Autonomy

    domainID: kuscia-domain-bob
    domainKeyData: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBaHJ1L1VibE9ZVzN2V3lVNldaOVdCbEc0dWJRQmZuNytBWnVEV0wvRmQzUDE1bktwCjRBQ3BGSlhnM1N3aUdlZkUzcnVmQ3QvdncvYWpmMWVYS1lVZVIvVVV3VWlYeERlRDY0Q2tSMGwvWjhETVpHUE8KSE8rSTMxUVR0VWVXOWdpWjNXWUk5dTZlNVpmNUNDUVBpcUVuZ2NsSVdEenRTMytmcStYY0ZwckNjRFA0YU9IZgprRmlUME1ZTWtmdDZiRHdDSHcxbGhiTUlDZmhId0pnSlo2djFYeURoTHMybVBUNUdBdmhDbW1EaFZqajdScDAzCjB4OVNkMjlCVnpSazRnNm9aK1BoNjgyY1FPWTYyTjdWNTM4M2pselhUb2UrTmQwWmllZXZZeU9QQS96eUxEdDAKWjJWT2xaUmFodHdWNHVKYUNwOWFUOGQrV203N3FmV0hpTFUwMVFJREFRQUJBb0lCQUFjTk1IZ3dnSitzeDBnMwo3SlBnT1BwZnNKRlhrSFIwWlFya2ZyMVlYQmRpWkU1SlZnYTVRaUFuci9zallpMkU2ZExXY3Y1NHRlM0ZyTXp2CllxUHpxYUFPZmFXWURRbGg5bStPN2dvbEdKdnZoVU1EempmSmVacG1waGxvdzhmZ3IxemRDRDhVUWhDMklYeUIKbHFha3hKS1FYRTd4OFdGd0xvVXFwSmd5UlZibDdmcGp1YWRzU08rbEtLSGFIVXpBMHNPUTMyOGxYLzhVR3plKwpUa0kyVE5Ob3ZyMERxYkYzcFUwS3BseHJ2QStxWUZOVCtjM29Pcm1KRzVXSStncVhYdVp4bWlBY2VNK3djOUxDCk9FejJ2Y3hna09ISGRDNkgxbFNRZ2tkUkhtM093QU9oUnBFWGszZEI1TmxlUnRpRnNnR0trMU5pL3M2WE5xOHoKOWg2R0h3RUNnWUVBdmZxS0xNM0VMVUpaOTFVQVZNTkFQNlJmRkFGb3l6RDdrMWRQQ0s3UWhVYlJXRHdzTXJMWQpBZXdXVHhObWx6NG95QXk2ajkwTFVwekJuZlEveWRpSWRSZUNkcDVvUDdGdWNhR1hKM09QZEZEMndxNkk1bXlJClhwb04yR0JCMVhzYXZpdThpdklhVkI1Q3JQNFNNZ2Era25TNE5xR3p6SjF2czNLWGJjL1RieUVDZ1lFQXRZNVAKQ1l6WXZXLzJ2REo1OFExSTBkTTV6L0t3czZJeWE1UURKTTZiNjVCYlVQMHk4QmtBdEVvOFRnNFBtV2JZaGN1TgpNRUVvczNIbkJpZnpsNkxlbTE2c1Q0OHVEL2pvaGFldGpma0NOeVBZb0hkZVlSMzNYeHJ0ZXhLLzIvSjZ4WU5QCmJkV1A1bWJNT0xYSTFFYXQwT1c0TkJwR1NHSTlJbXRxUGZWMzB6VUNnWUJjTU1kNnhJT3RudVEvcE8wYk5RRHAKb1Y5T092emFsYk9QcGEvQnUrdU9zWFlIaG5QQVNvK09KejRRTTQ3MldBQzhTNGtCSlRoSVo2K0JjalMrUTZpOApnYU1hNHZZZDZvRjQvUHgzOVprb3pkMWhUZ2M3SW5IdXpuMW5naGFRZlVQV0F5MWtrK1g0NmhKYkZwUkgySVFFCldFWElwU0cyYXJQNDllUE1NeTBjWVFLQmdRQ0srVkg2NTN1SkZzbHhxZG01OFFkS3hqczh1SE1XTGhRV1VRaFAKQm5CSDB3cHpaajIxbUEzMzg5TlJsR1hRY085UkMwMGFJT1o4NWJXSCt0RDF3OUJPY2h2SUVydVpzbGlhNW8xdApYYXlhZEsvL3RSL2ppMEt0NURqZ3VxdHVPNkJLekliaWRsVmVjbFhsR3hHTm5FUzA0UU10cnVjWnhVa3lyYkozCmx3eVArUUtCZ0ZwMjhLSFQ1b3VLVGNnWXpmVGlkd0EwV2h5VVBjaXh5RkFFZEFSbngrc1gvK1ZtdDhMb04yUWIKOWdLbTR6UW50bVg4NWNEWDdwYm5OU1hweGFaRGhTb1A4TFFrb0xxV0x3TjJZbjVvU09WOGFvdk5ZNUdoeWlwMAo4QWU0ZlQ1cHRiVkxNajQxdzY2Y2w4M1ZIUjR4cTBZSHVjTmMrZElrZ25ncXRNNVRHZVVHCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="

    logLevel: DEBUG

    runtime: runk
    runk:
      namespace: kuscia-domain-bob
      dnsServers: []
      kubeconfigFile: ""

    capacity:
      cpu: 2
      memory: 4Gi
      storage: 10Gi

    image:
      pullPolicy: ""
      defaultRegistry: ""
      registries:
        - name: ""
          endpoint: ""
          username: ""
          password: ""

    datastoreEndpoint: ""
    protocol: NOTLS

---
apiVersion: v1
kind: Service
metadata:
  name: kuscia-bob
  namespace: kuscia-domain-bob
  labels:
    app: kuscia-bob
spec:
  selector:
    app: kuscia-bob
  type: ClusterIP
  ports:
    - name: envoy
      port: 1080
      protocol: TCP
      targetPort: 1080
    - name: envoy-internal
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: kusciaapi
      port: 8082
      protocol: TCP
      targetPort: 8082

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuscia-service-role
  namespace: kuscia-domain-bob
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuscia-service-rolebinding
  namespace: kuscia-domain-bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuscia-service-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kuscia-domain-bob
