{
 "title": "machine_center",
 "description": "使用 Node Exporter，展示主机重要指标。包含：CPU 内存 磁盘 IO 网络 温度等监控指标。",
 "tags": [
  "kubernetes",
  "node",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "maxmount",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~\"${instance}:9091\",fstype=~\"ext4|xfs\"}) by (mountpoint))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "System runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"${instance}:9091\"}"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"${instance}:9091\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU utilization (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"${instance}:9091\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"${instance}:9091\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\"${instance}:9091\"} / (node_memory_MemTotal_bytes{instance=~\"${instance}:9091\"})))* 100)"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filefd_allocated{instance=~\"${instance}:9091\"})/sum(node_filefd_maximum{instance=~\"${instance}:9091\"})"
    }
   ]
  },
  {
   "title": "Root partition usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:9091\",mountpoint=\"/etc/hostname\"} * 100) / node_filesystem_size_bytes {instance=~\"${instance}:9091\",mountpoint=\"/etc/hostname\"}))"
    }
   ]
  },
  {
   "title": "Maximum partition ($maxmount) usage",
   "type": "stat",
   "description": "通过变量maxmount获取最大的分区。",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{instance=~\"${instance}:9091\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"${instance}:9091\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"}))"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"${instance}:9091\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average system load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"${instance}:9091\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"${instance}:9091\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"${instance}:9091\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {instance=~\"${instance}:9091\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free space in each zone",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance='$instance:9091',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance='$instance:9091',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance='$instance:9091',fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU usage, i/o operation time per second (%) of disk",
   "type": "graph",
   "description": "这里CPU使用率、磁盘每秒IO操作耗时使用率 % 此图每根线的含义：\n\nSystem，是CPU系统部分CPU时间片占总CPU时间片的百分比，也就是CPU系统部分的CPU使用率%\nUser，是CPU User部分CPU时间片占总CPU时间片的百分比，也就是CPU User部分的CPU使用率%\nIowait，是CPU Iowait部分CPU时间片占总CPU时间片的百分比，也就是CPU Iowait部分的CPU使用率%\n\n{{device}}_每秒I/O操作% 这根线是每个设备（如vda），IO操作的时间占总IO时间的占比，也就是此设备的IO使用率 %\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"${instance}:9091\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"${instance}:9091\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"${instance}:9091\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_I/O operations per second%"
    }
   ]
  },
  {
   "title": "Memory information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:9091\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"${instance}:9091\"} - node_memory_MemAvailable_bytes{instance=~\"${instance}:9091\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"${instance}:9091\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk read / write rate (IOPs)",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk read / write capacity size",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk IO read / write time",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"${instance}:9091\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"${instance}:9091\",device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_in Download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"${instance}:9091\",device!~'tap.*'}[5m])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "TCP connection",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$instance:9091'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$instance:9091'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$instance:9091'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$instance:9091'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$instance:9091'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$instance:9091'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Average RTT of a cluster (without the master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "ss_rtt{instance=\"${instance}:9091\"}",
     "legendFormat": "{${instance}}_avg_rtt"
    }
   ]
  },
  {
   "title": "Total bytes from upstream connections (without the master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_tx_bytes_total{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_cx_tx_bytes_total"
    },
    {
     "expr": "envoy_cluster_upstream_cx_rx_bytes_total{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_cx_rx_bytes_total"
    },
    {
     "expr": "envoy_cluster_upstream_cx_total{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_cx_total"
    }
   ]
  },
  {
   "title": "Error rate of upstream connections (without the master)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_connect_fail{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_cx_connect_fail_rate"
    },
    {
     "expr": "envoy_cluster_upstream_cx_connect_timeout{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_cx_connect_timeout_rate"
    },
    {
     "expr": "ss_retran_rate{instance=\"${instance}:9091\"}",
     "legendFormat": "{${instance}}_retran_rate"
    },
    {
     "expr": "envoy_cluster_upstream_rq_timeout{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}/envoy_cluster_upstream_rq_total{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"} ",
     "legendFormat": "{${instance}}_rq_timeout_rate"
    },
    {
     "expr": "envoy_cluster_health_check_failure{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}/envoy_cluster_health_check_attempt{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_health_check_fail_rate"
    }
   ]
  },
  {
   "title": "Total upstream requests (without the master)",
   "type": "timeseries",
   "description": "The total number of end-to-end requests",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_total{instance=\"${instance}:9091\",envoy_cluster_name=~\".+-to-.+-http\"}",
     "legendFormat": "{${instance}}_rq_total"
    }
   ]
  },
  {
   "title": "Total retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "targets": [
    { "expr": "ss_retrans", "legendFormat": "{${instance}}_retrans" }
   ]
  }
 ]
}