apiVersion: v1
kind: Service
metadata:
  name: service-alice1
  namespace: alice1
spec:
  selector:
    app: kuscia-alice
  type: ClusterIP
  ports:
    - name: envoy
      port: 1080
      protocol: TCP
      targetPort: 1080
    - name: envoy-internal
      port: 80
      protocol: TCP
      targetPort: 80
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: kusciaapi
      port: 8082
      protocol: TCP
      targetPort: 8082
